[build]
  command = "hugo"
  publish = "public"

[build.environment]
  NODE_ENV = "production"
  GO_VERSION = "1.16"
  TZ = "Canada/Montreal"

[context.production.environment]
  HUGO_VERSION = "0.92.0"
  HUGO_ENV = "production"